stages:
- prepare

front:install:
  stage: prepare
  image: node
  tags:
  - Interne
  script:
  - npm install
  - npm run build:lib
  - cp -r src/assets dist/ngx-frogger/assets
  - cd dist/ngx-frogger
  - npm publish
